title = "this is the configuration file of the plugin Arduino"

com_port = "COM24"
ip_address = "172.17.50.236"
ip_port = 31336

[esp32]
ip_address = "172.17.50.53"

[esp32.pins]
heater_pin = 18
fan_pin = 17

[presets]
preset_for_colorsynthesizer = "ArduinoLED"

[LED]
[LED.pins]
red_pin = 6
green_pin = 4
blue_pin = 5

[LCD]
address = 0x27
cols = 16
rows = 2

[servo]
pin = 2
pos_1 = 55
pos_2 = 80

[FanHeater]
[FanHeater.pins]
heater_pin = 9
heater_fan_pin = 8

[max31865]
#Broches SPI pour le capteur MAX31865 / PT100
#Vameirs par défaut : Nano ESP32 en mode GPIO Legacy
sck_pin  = 48
miso_pin = 47
mosi_pin = 38
cs_pin   = 21

